pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }

        stage ('Build') {
            steps {
                sh 'cd Core-Java/DateTimeCalculator'
                sh 'mvn -f Core-Java/DateTimeCalculator clean'
                sh 'mvn -f Core-Java/DateTimeCalculator test'
                sh 'mvn -f Core-Java/DateTimeCalculator install'
            }
            post {
                success {
                    junit 'Core-Java/DateTimeCalculator/target/surefire-reports/*.xml' 
                }
            }
        }
    }
}